server:
  port: 9020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: Faiz@8488
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        format_sql: true
        use_sql_comments: true
