server:
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: "{cipher}30f4f0de08676172ccb1f56b9b4a8ea0c7b31ec19a5a55b86a494a3d650613b2"
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        format_sql: true
        use_sql_comments: true
